### ISSUE TITLE
How to add more device into configuration.yaml

### ISSUE THREAD

**Issue by Feryy** [Rsclub22/home-assistant-fht#1]
Hi, 
 I have the following items in my configuration:
climate:
  - platform: fht_heating
    address: "192.168.88.197:8086"
    dev_name: "FHT_LivingRoom"

I would like to add another FHT device (FHT_BathRoom). How do I do this?
Tanks.

**Comment by tarek-yashi** [comment]
Hi! 

You can add more devices like this:

```
climate:
  - platform: fht_heating
    address: "192.168.88.197:8086"
    dev_name: "FHT_LivingRoom"
  - platform: fht_heating
    address: "192.168.88.197:8086"
    dev_name: "FHT_BathRoom"
```
